### 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）/ script (脚本)
mode: rule

### 混合端口 HTTP和SOCKS5用一个端口
mixed-port: 7890

### HTTP 代理端口
port: 7890

### SOCKS5 代理端口
#socks-port: 7891

### Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
#redir-port: 7892

### 允许局域网的连接（可用来共享代理）
allow-lan: false

### 地址绑定，仅允许特定地址，仅在将allow-lan设置为true时适用
### "*": 绑定所有IP地址
### 192.168.122.11: 绑定单个IPv4地址
### "[aaaa::a8aa:ff:fe09:57d8]": 绑定单个IPv6地址
#bind-address: "*"

### 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
### 5 个级别：silent / error / warning / info / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

### RESTful API 网页控制端的口令 (可选)
#secret: ""

### Clash 的 RESTful API，网页控制端
external-controller: '127.0.0.1:9090'
# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# http://127.0.0.1:9090/ui/#/
# external-ui: folder
# yacd面板：  https://github.com/haishanh/yacd
# Razord面板：http://clash.razord.top/#/proxies
# external-ui: dashboard

### 启用ipv6代理
ipv6: true

### 实验性功能
experimental:
  ### 忽略 DNS 解析失败，默认值为 true
  ignore-resolve-fail: true
  ### 绑定接口
  #interface-name: en0 

### 实验性功能 hosts, 支持通配符 *.clash.dev 甚至 *.foo.*.example.com，静态的域名比通配域名具有更高的优先级
### 注意: hosts 在 fake-ip 模式下不生效
#hosts:
# '*.clash.dev': 127.0.0.1
# 'alpha.clash.dev': '::1'

### 本地 SOCKS5 / HTTP(S) 服务认证
#authentication:
# - "user1:pass1"

### DNS设置
dns:
  ### 是否启用dns
  enable: true
  ### 是否启用ipv6
  ipv6: true
  ### 监听端口
  listen: 0.0.0.0:7874
  ### 模式：redir-host或fake-ip
  enhanced-mode: redir-host
  ### fake-ip分配的IP段
  #fake-ip-range: 198.18.0.1/16
  ### fake ip 白名单列表，以下内容返回真实IP
  #fake-ip-filter:
     #- '*.lan'
     #- localhost.ptlogin2.qq.com
  nameserver:
     # 阿里 DoH DNS
     - https://223.5.5.5/dns-query
     # 阿里 DoH DNS
     - https://dns.alidns.com/dns-query
     # 腾讯 DoH DNS
     - https://doh.pub/dns-query
  fallback:
     - tls://dns.rubyfish.cn:853
     - tls://1.0.0.1:853
     - tls://dns.google:853
     #- https://dns.rubyfish.cn/dns-query
     #- https://cloudflare-dns.com/dns-query
     #- https://dns.google/dns-query
  fallback-filter:
     geoip: true
     geoip-code: CN
     geosite:
      - gfw
      - "!cn"
     ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
      - 240.0.0.0/4
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32

# 1. clash DNS 请求逻辑：
#   (1) 当访问一个域名时， nameserver 与 fallback 列表内的所有服务器并发请求，得到域名对应的 IP 地址。
#   (2) clash 将选取 nameserver 列表内，解析最快的结果。
#   (3) 若解析结果中，IP 地址属于 国外，那么 clash 将选择 fallback 列表内，解析最快的结果。
#
#   因此，我在 nameserver 和 fallback 内都放置了无污染、解析速度较快的国内 DNS 服务器，以达到最快的解析速度。
#   但是 fallback 列表内服务器会用在解析境外网站，为了结果绝对无污染，我仅保留了支持 DoT/DoH 的两个服务器。
#
# 2. clash DNS 配置注意事项：
#   (1) 如果您为了确保 DNS 解析结果无污染，请仅保留列表内以 tls:// 或 https:// 开头的 DNS 服务器，但是通常对于国内域名没有必要。
#   (2) 如果您不在乎可能解析到污染的结果，更加追求速度。请将 nameserver 列表的服务器插入至 fallback 列表内，并移除重复项。
#
# 3. 关于 DNS over HTTPS (DoH) 和 DNS over TLS (DoT) 的选择：
#   对于两项技术双方各执一词，而且会无休止的争论，各有利弊。各位请根据具体需求自行选择，但是配置文件内默认启用 DoT，因为目前国内没有封锁或管制。
#   DoH: 以 https:// 开头的 DNS 服务器。拥有更好的伪装性，且几乎不可能被运营商或网络管理封锁，但查询效率和安全性可能略低。
#   DoT: 以 tls:// 开头的 DNS 服务器。拥有更高的安全性和查询效率，但端口有可能被管制或封锁。
#   若要了解更多关于 DoH/DoT 相关技术，请自行查阅规范文档。
